#version: "3"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../project:/app
  app:
    build: services/php
    volumes:
      - ../project:/app
  db:
    image: mariadb:latest
    env_file: ../.env
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  db-admin:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}
